version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mapillary"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    restart: always
    build: .
    ports:
    - "5000:5000"
    depends_on:
      postgres:
         condition: service_healthy
    entrypoint: ["sh", "start.sh"]
